### ISSUE TITLE
ModuleNotFoundError: No Module named 'sh'

### ISSUE THREAD

**Issue by ChrisRollz** [codelv/enaml-native-cli#18]
Hi, thanks for creating this. I played around with enaml-native playground and enjoyed. Now I'm trying to install and use enaml-native to create my new application. I am running Ubuntu 18.04. I was able to get conda up and running (by installing the full Anaconda linux package). Now upon trying to create an app I receive the following:

```
`~/Documents/MyApps/EnamlProjects$ enaml-native create app

Traceback (most recent call last):
  File "/home/chris/anaconda3/bin/enaml-native", line 6, in <module>
    from enamlnativecli.main import main
  File "/home/chris/anaconda3/lib/python3.7/site-packages/enamlnativecli/main.py", line 14, in <module>
    import sh
ModuleNotFoundError: No module named 'sh'
`
```

**Comment by ChrisRollz** [comment]
Made progress with
```
pip install sh
pip install atom
pip install cookiecutter
```

Challenge is now No module named 'ruamel'

```

/Documents/MyApps/EnamlProjects$ pip install ruamel
Collecting ruamel
  Could not find a version that satisfies the requirement ruamel (from versions: )
No matching distribution found for ruamel

```

**Comment by ChrisRollz** [comment]
More progress. Able to execute enaml-native create app now after running:


```
$ sudo apt-get install python-yaml
$ pip install ruamel.base
$ pip install ryd
```

Results:

```
~/Documents/MyApps/EnamlProjects$ enaml-native create app
Warning: environment.yml does not exist. Using the default.
python_version [3.6]: y
author []: Chris
app_name [Hello World]: Hello world
project_name [Helloworld]: helloworld
app_version [1]: 1
app_version_code [1]: 1
bundle_id [com.example.helloworld]: com.example.helloworld
bundle_path [com/example/helloworld]: com/example/helloworld
color_primary [#3574a3]: 
color_primary_dark [#004981]: 
color_accent [#97c024]: 
android_ndk [~/Android/Sdk/ndk-bundle]: 
android_sdk_version [27]: 
android_min_sdk_version [21]: 
android_target_sdk_version [27]: 
android_build_tools_version [26.0.2]: 
google_maps_api_key [none]: 
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python=y

Current channels:

  - https://conda.anaconda.org/codelv/linux-64
  - https://conda.anaconda.org/codelv/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Exception in thread background thread for pid 7342:
Traceback (most recent call last):
  File "/home/chris/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/chris/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/chris/anaconda3/bin/conda create -p venv -c codelv --use-local --yes python=y enaml-native

  STDOUT:


  STDERR:


Traceback (most recent call last):
  File "/tmp/tmpexitm3xf.py", line 14, in <module>
    p.wait()
  File "/home/chris/anaconda3/lib/python3.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/chris/anaconda3/bin/conda create -p venv -c codelv --use-local --yes python=y enaml-native

  STDOUT:


  STDERR:

ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Traceback (most recent call last):
  File "/home/chris/anaconda3/bin/enaml-native", line 10, in <module>
    sys.exit(main())
  File "/home/chris/anaconda3/lib/python3.7/site-packages/enamlnativecli/main.py", line 1657, in main
    EnamlNativeCli().start()
  File "/home/chris/anaconda3/lib/python3.7/site-packages/enamlnativecli/main.py", line 1651, in start
    cmd.run(self.args)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/enamlnativecli/main.py", line 177, in run
    overwrite_if_exists=args.overwrite_if_exists)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/cookiecutter/main.py", line 94, in cookiecutter
    output_dir=output_dir
  File "/home/chris/anaconda3/lib/python3.7/site-packages/cookiecutter/generate.py", line 376, in generate_files
    delete_project_on_failure
  File "/home/chris/anaconda3/lib/python3.7/site-packages/cookiecutter/generate.py", line 236, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/cookiecutter/hooks.py", line 144, in run_hook
    run_script_with_context(script, project_dir, context)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/cookiecutter/hooks.py", line 128, in run_script_with_context
    run_script(temp.name, cwd)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/cookiecutter/hooks.py", line 91, in run_script
    'Hook script failed (exit status: {})'.format(exit_status)
cookiecutter.exceptions.FailedHookException: Hook script failed (exit status: 1)

```

**Comment by ChrisRollz** [comment]
Success! I am very new to this, apologies if this is clearcut for other users. I ran enamle-native create app again and just hit enter thoughout.

In summary, my process for getting enaml-native to execute enaml-native create app on Ubuntu 18.04 in terminal:

1. install Anaconda (not miniconda), (yes to adding to bashrc)
2. conda install -c codelv enaml-native-cli
2. pip install sh
3. pip install atom
4. pip install cookiecutter
5. sudo apt-get install python-yaml
6. pip install ruamel.base
7. pip install ryd
8. enaml-native create app (enter to all defaults)
[INFO] App created successfully!
