### ISSUE TITLE
Error: sh.CommandNotFound: ./gradlew

### ISSUE THREAD

**Issue by null0nil** [codelv/enaml-native-cli#21]
On my Linux machine, I ran "enaml-native build-android" and got the error below:
```
[DEBUG]:   -> running cd android
[DEBUG]:   -> running  cd /share/Projects/android/enaml/helloworld2
Traceback (most recent call last):
  File "/home/HQ/tchang/miniconda3/envs/enaml/bin/enaml-native", line 8, in <module>
    sys.exit(main())
  File "/home/HQ/tchang/miniconda3/envs/enaml/lib/python3.8/site-packages/enamlnativecli/main.py", line 1772, in main
    EnamlNativeCli().start()
  File "/home/HQ/tchang/miniconda3/envs/enaml/lib/python3.8/site-packages/enamlnativecli/main.py", line 1766, in start
    cmd.run(self.args)
  File "/home/HQ/tchang/miniconda3/envs/enaml/lib/python3.8/site-packages/enamlnativecli/main.py", line 1271, in run
    gradlew = sh.Command('gradlew.bat' if IS_WIN else './gradlew')
  File "/home/HQ/tchang/miniconda3/envs/enaml/lib/python3.8/site-packages/sh.py", line 1202, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: ./gradlew
```
The fix is:
```
   chmod a+x android/gradlew
```

**Comment by frmdstryr** [comment]
Thanks! Could you submit a pr that runs that command automatically on non windows systems?

**Comment by null0nil** [comment]
No problem.   I can take a look at how OS-detection can be done and submit a pr later this week.

**Comment by wasimafser** [comment]
Anything done yet ? I'm on mac and I faced the same problem. Just letting you people know.

EDIT : Just found out that, fixing the permissions cleared the error

EDIT 2 : Fixed it by running a command to fix permission before actually executing './gradlew' , check #22 @frmdstryr
