### ISSUE TITLE
environment.yaml not properly generated with command "enaml-native create app"

### ISSUE THREAD

**Issue by bobosui** [codelv/enaml-native-cli#23]
I encountered a problem when trying to run enaml-native-cli on Windows+miniconda3+python3.7.6. The error shows environment.yaml is not properly generated. Would someone check this?
Thanks.
The error message is print out below.
```
self.package=environment.yml
Warning: environment.yml does not exist. Using the default.
cmd <enamlnativecli.main.Create object at 0x0000016C04AB5908>
template c:\miniconda3\envs\android\lib\site-packages\enamlnativecli\templates\app
python_version [3.7]: Traceback (most recent call last):
  File "c:\miniconda3\envs\android\lib\site-packages\click\termui.py", line 100, in prompt_func
    return f('')
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\miniconda3\envs\android\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda3\envs\android\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda3\envs\android\Scripts\enaml-native.exe\__main__.py", line 7, in <module>
  File "c:\miniconda3\envs\android\lib\site-packages\enamlnativecli\main.py", line 1775, in main
    EnamlNativeCli().start()
  File "c:\miniconda3\envs\android\lib\site-packages\enamlnativecli\main.py", line 1769, in start
    cmd.run(self.args)
  File "c:\miniconda3\envs\android\lib\site-packages\enamlnativecli\main.py", line 261, in run
    overwrite_if_exists=args.overwrite_if_exists)
  File "c:\miniconda3\envs\android\lib\site-packages\cookiecutter\main.py", line 82, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "c:\miniconda3\envs\android\lib\site-packages\cookiecutter\prompt.py", line 219, in prompt_for_config
    val = read_user_variable(key, val)
  File "c:\miniconda3\envs\android\lib\site-packages\cookiecutter\prompt.py", line 26, in read_user_variable
    return click.prompt(var_name, default=default_value)
  File "c:\miniconda3\envs\android\lib\site-packages\click\termui.py", line 116, in prompt
    value = prompt_func(prompt)
  File "c:\miniconda3\envs\android\lib\site-packages\click\termui.py", line 107, in prompt_func
    raise Abort()
click.exceptions.Abort
```

**Comment by bobosui** [comment]
OK, I reread the atom module and got some understanding on this part.
