### ISSUE TITLE
Cookiecutter script error

### ISSUE THREAD

**Issue by dunossauro** [codelv/enaml-native-cli#26]
```sh
$ enaml-native create app
/home/dunossauro/.pyenv/versions/3.7.7/lib/python3.7/site-packages/atom/scalars.py:227: FutureWarning: Unicode is deprecated and will be removed in atom 0.6.0
  warnings.warn(FutureWarning(msg))
Warning: environment.yml does not exist. Using the default.
python_version [3.7]: 
author []: 
app_name [Hello World]: 
domain [com.example]: 
bundle_id [com.example.helloworld]: 
project_name [HelloWorld]: 
bundle_path [com/example/helloworld]: 
app_version [1.0]: 
app_version_code [1]: 
color_primary [#3574a3]: 
color_primary_dark [#004981]: 
color_accent [#97c024]: 
user_home [/home/dunossauro]: 
android_sdk [/home/dunossauro/Android/Sdk/]: 
android_ndk [/home/dunossauro/Android/Sdk//ndk-bundle]: 
android_sdk_version [29]: 
android_min_sdk_version [21]: 
android_target_sdk_version [29]: 
google_maps_api_key [none]: 

/home/dunossauro/.pyenv/versions/3.7.7/lib/python3.7/site-packages/atom/scalars.py:227: FutureWarning: Unicode is deprecated and will be removed in atom 0.6.0
  warnings.warn(FutureWarning(msg))

EnvironmentSectionNotValid: The following sections on '/home/dunossauro/git/mobile-test/HelloWorld/environment.yml' are invalid and will be ignored:
 - bundle_id
 - excluded
 - android
 - ios

Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/home/dunossauro/.conda/envs/helloworld/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/dunossauro/git/mobile-test/HelloWorld/condaenv.zjc31ua7.requirements.txt']
Pip subprocess output:
Collecting enaml-native-cli
  Using cached enaml_native_cli-2.3.1-py2.py3-none-any.whl (365 kB)
Collecting atom
  Using cached atom-0.5.1-cp37-cp37m-manylinux1_x86_64.whl (137 kB)
Collecting ruamel.yaml
  Using cached ruamel.yaml-0.16.10-py2.py3-none-any.whl (111 kB)
Processing /home/dunossauro/.cache/pip/wheels/f7/f7/89/54a4ecfce7cc7490e56c55c48b7f72d01a032f15bcaf1dac00/pbs-0.110-py3-none-any.whl
Collecting cookiecutter
  Using cached cookiecutter-1.7.2-py2.py3-none-any.whl (34 kB)
Collecting sh
  Using cached sh-1.13.1-py2.py3-none-any.whl (40 kB)
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9"
  Using cached ruamel.yaml.clib-0.2.0-cp37-cp37m-manylinux1_x86_64.whl (547 kB)
Collecting poyo>=0.5.0
  Using cached poyo-0.5.0-py2.py3-none-any.whl (10 kB)
Collecting requests>=2.23.0
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Processing /home/dunossauro/.cache/pip/wheels/7c/26/30/5f3d95da00fe94d0c4a5ec5b4ffd2e1ae18545f5fa61752e52/python_slugify-4.0.0-py2.py3-none-any.whl
Collecting MarkupSafe<2.0.0
  Using cached MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl (27 kB)
Collecting six>=1.10
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting Jinja2<3.0.0
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting binaryornot>=0.4.4
  Using cached binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
Collecting jinja2-time>=0.2.0
  Using cached jinja2_time-0.2.0-py2.py3-none-any.whl (6.4 kB)
Collecting click>=7.0
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/dunossauro/.conda/envs/helloworld/lib/python3.7/site-packages (from requests>=2.23.0->cookiecutter->enaml-native-cli->-r /home/dunossauro/git/mobile-test/HelloWorld/condaenv.zjc31ua7.requirements.txt (line 1)) (2020.4.5.1)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Collecting text-unidecode>=1.3
  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Collecting arrow
  Using cached arrow-0.15.6-py2.py3-none-any.whl (47 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Installing collected packages: atom, ruamel.yaml.clib, ruamel.yaml, pbs, poyo, chardet, idna, urllib3, requests, text-unidecode, python-slugify, MarkupSafe, six, Jinja2, binaryornot, python-dateutil, arrow, jinja2-time, click, cookiecutter, sh, enaml-native-cli
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 arrow-0.15.6 atom-0.5.1 binaryornot-0.4.4 chardet-3.0.4 click-7.1.2 cookiecutter-1.7.2 enaml-native-cli-2.3.1 idna-2.9 jinja2-time-0.2.0 pbs-0.110 poyo-0.5.0 python-dateutil-2.8.1 python-slugify-4.0.0 requests-2.23.0 ruamel.yaml-0.16.10 ruamel.yaml.clib-0.2.0 sh-1.13.1 six-1.15.0 text-unidecode-1.3 urllib3-1.25.9

#
# To activate this environment, use
#
#     $ conda activate helloworld
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Could not create a link to the env!
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Traceback (most recent call last):
  File "/home/dunossauro/.pyenv/versions/3.7.7/bin/enaml-native", line 10, in <module>
    sys.exit(main())
  File "/home/dunossauro/.pyenv/versions/3.7.7/lib/python3.7/site-packages/enamlnativecli/main.py", line 1772, in main
    EnamlNativeCli().start()
  File "/home/dunossauro/.pyenv/versions/3.7.7/lib/python3.7/site-packages/enamlnativecli/main.py", line 1766, in start
    cmd.run(self.args)
  File "/home/dunossauro/.pyenv/versions/3.7.7/lib/python3.7/site-packages/enamlnativecli/main.py", line 259, in run
    overwrite_if_exists=args.overwrite_if_exists)
  File "/home/dunossauro/.pyenv/versions/3.7.7/lib/python3.7/site-packages/cookiecutter/main.py", line 106, in cookiecutter
    output_dir=output_dir,
  File "/home/dunossauro/.pyenv/versions/3.7.7/lib/python3.7/site-packages/cookiecutter/generate.py", line 362, in generate_files
    repo_dir, 'post_gen_project', project_dir, context, delete_project_on_failure
  File "/home/dunossauro/.pyenv/versions/3.7.7/lib/python3.7/site-packages/cookiecutter/generate.py", line 237, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "/home/dunossauro/.pyenv/versions/3.7.7/lib/python3.7/site-packages/cookiecutter/hooks.py", line 131, in run_hook
    run_script_with_context(script, project_dir, context)
  File "/home/dunossauro/.pyenv/versions/3.7.7/lib/python3.7/site-packages/cookiecutter/hooks.py", line 115, in run_script_with_context
    run_script(temp.name, cwd)
  File "/home/dunossauro/.pyenv/versions/3.7.7/lib/python3.7/site-packages/cookiecutter/hooks.py", line 87, in run_script
    'Hook script failed (exit status: {})'.format(exit_status)
cookiecutter.exceptions.FailedHookException: Hook script failed (exit status: 1)
```

OS: Archlinux

**Comment by frmdstryr** [comment]
I'm guessing it can't find the proper venv path since it's being run from an env

If you comment out these lines:
https://github.com/codelv/enaml-native-cli/blob/master/enamlnativecli/templates/app/hooks/post_gen_project.py#L36-L38

Edit ~~It should work alright~~, you may need to manually create a symlink from the env to `venv`.

That should probably be a warning instead of an error.
