### ISSUE TITLE
Setuptools broke something

### ISSUE THREAD

**Issue by frmdstryr** [codelv/enaml-native-cli#3]
```
[INFO]:    STDOUT:                                                                                 
        Traceback (most recent call last):      
  File "setup.py", line 12, in <module> 
    import setuptools   
  File "/home/jrm/.local/share/python-for-android/build/python-installs/enaml-native/setuptools/__init__.py", line 5, in <module>       
    import distutils.core       
  File "venv/lib/python2.7/distutils/__init__.py", line 23, in <module>     
    __version__ = real_distutils.__version__    
AttributeError: 'module' object has no attribute '__version__'
[INFO]:    STDERR:


```

**Comment by frmdstryr** [comment]
Deleted the whole `~/.local/share/python-for-android/build` folder and it worked
